"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Goto Downloads"

[[manager.prepend_keymap]]
on = ["c", "y"]
run = '''shell 'yek "$@" | pbcopy' '''
desc = "Yek selected files and directories"

[[manager.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[manager.prepend_keymap]]
on = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on = ["p", "d"]
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[manager.prepend_keymap]]
on = ["p", "g"]
run = "shell --confirm --block lazygit"
desc = "lazygit"

[[manager.prepend_keymap]]
on = ["p", "s"]
run = 'shell "$SHELL" --confirm --block'
desc = "shell"

[[manager.prepend_keymap]]
on = ["c", "a"]
run = "plugin ouch"
desc = "Compress with ouch"

# [[manager.prepend_keymap]]
# on = ["c", "a"]
# run = "plugin compress"
# desc = "Archive selected files"
