"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "plugin vcs-files"
desc = "Show Git file changes"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Goto Downloads"

[[mgr.prepend_keymap]]
on = ["g", "j"]
run = "plugin zoxide"
desc = "Jump to a directory via zoxide"

[[mgr.prepend_keymap]]
on = ["g", "J"]
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[mgr.prepend_keymap]]
on = ["c", "y"]
run = '''shell 'yek "$@" | pbcopy' '''
desc = "Yek selected files and directories"

[[mgr.prepend_keymap]]
on = ["g", "s", "g"]
run = "shell --confirm --block lazygit"
desc = "Run lazygit"

[[mgr.prepend_keymap]]
on = ["g", "s", "e"]
run = """shell --confirm --block 'nvim "$PWD"'"""
desc = "Run nvim"

[[mgr.prepend_keymap]]
on = ["c", "a"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = ["c", "D"]
run = "plugin diff"
desc = "Copy the diff of the selected with the hovered file"

[[mgr.prepend_keymap]]
on = ["c", "r"]
run = "plugin path-from-root"
desc = "Copies path from git root"

[[mgr.prepend_keymap]]
on = ["n"]
run = 'shell "$SHELL" --confirm --block'
desc = "Run shell"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"

# [[mgr.prepend_keymap]]
# on = ["1"]
# run = "plugin relative-motions 1"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["2"]
# run = "plugin relative-motions 2"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["3"]
# run = "plugin relative-motions 3"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["4"]
# run = "plugin relative-motions 4"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["5"]
# run = "plugin relative-motions 5"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["6"]
# run = "plugin relative-motions 6"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["7"]
# run = "plugin relative-motions 7"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["8"]
# run = "plugin relative-motions 8"
# desc = "Move in relative steps"

# [[mgr.prepend_keymap]]
# on = ["9"]
# run = "plugin relative-motions 9"
# desc = "Move in relative steps"
