[project]
name = "dotfiles"
version = "0.1.0"
description = "This is my dotfiles development environment"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argcomplete>=3.6.3",
    "autocorrect-py>=2.14.0",
    "fire>=0.7.1",
    "loguru>=0.7.3",
    "rich>=14.2.0",
    "tiktoken>=0.12.0",
    "youtube-transcript-api>=1.2.3",
]
