# espanso configuration file
show_notifications: false
toggle_key: OFF
matches:
  # Dates
  - trigger: "#sd"
    replace: "{{shortdate}}"
    vars:
      - name: shortdate
        type: date
        params:
          format: "%y%m%d"
  - trigger: "#fd"
    replace: "{{fulldate}}"
    vars:
      - name: fulldate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "#st"
    replace: "{{shorttime}}"
    vars:
      - name: shorttime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: "#ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "ifconfig | grep 'inet ' | grep -Fv 127.0.0.1 | awk '{print $2}'"
          shell: bash

  # Roam
  - trigger: "ã€ã€"
    replace: "[[$|$]]"
  - trigger: "ï¼ˆï¼ˆ"
    replace: "(($|$))"
  - trigger: "ï¼›ï¼›"
    replace: ;;

  # Software abbreviations
  - trigger: "#rm"
    replace: "Roam Research"

  # Mac symbols

  # My
  - trigger: "#my"
    form: |
      ğŸ™‹â€â™‚ï¸ Hiï¼Œå¾ˆé«˜å…´è®¤è¯†ä½ ï½ æˆ‘çš„åšå®¢æ˜¯ ğŸ‘‰ {{blog}} ä½ ä¹Ÿåœ¨ Telegram ä¸Šæ‰¾åˆ°æˆ‘ ğŸ‘‰ {{telegram}}
    form_fields:
      text:
        multiline: true

  - trigger: "#@m"
    form: |
      {{Mail}}
    form_fields:
      text:
        multiline: true
