[tools]
"cargo:bartib" = "latest"
"cargo:choose" = "latest"
"cargo:counts" = "latest"
"cargo:fd-find" = "latest"
"cargo:gfold" = "latest"
"cargo:https://github.com/bodo-run/yek" = "latest"
"cargo:https://github.com/hanshuaikang/Nping" = "latest"
"cargo:https://github.com/KSXGitHub/parallel-disk-usage" = "latest"
"cargo:https://github.com/lotabout/rargs.git" = "latest"
"cargo:https://github.com/Nukesor/pueue" = "latest"
"cargo:https://github.com/sirwart/ripsecrets" = "latest"
"cargo:https://github.com/svenstaro/miniserve" = "latest"
"cargo:https://github.com/yarrow/zet" = "latest"
"cargo:https://github.com/yshavit/mdq" = "latest"
"cargo:jaq" = "latest"
"cargo:koji" = "latest"
"cargo:legdur" = "latest"
"cargo:lychee" = "latest"
"cargo:netscanner" = "latest"
"cargo:rip2" = "latest"
"cargo:ripgrep" = "latest"
"cargo:rnr" = "latest"
"cargo:rust-parallel" = "latest"
"cargo:sd" = "latest"
"cargo:spacer" = "latest"
"cargo:watchexec-cli" = "latest"
"gem:kamal" = "latest"
"go:code.gitea.io/tea" = "latest"
"go:github.com/josephburnett/jd" = "latest"
"go:github.com/merschformann/gotz" = "latest"
"go:github.com/muesli/duf" = "latest"
"go:github.com/wader/fq" = "latest"
"go:github.com/zyedidia/eget" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:autocorrect-node" = "latest"
"pipx:argcomplete" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"
"pipx:vastai" = "latest"
bun = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
zig = "latest"

[settings]
trusted_config_paths = ['~/Developer']
experimental = true

[settings.npm]
bun = true

[settings.pipx]
uvx = true
