[tools]
# Language Tools
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
zig = "latest"

# Package Management Tools
cargo-binstall = "latest"
uv = "latest"

# CI / CD Tools
"cargo:https://github.com/sirwart/ripsecrets" = "latest"
"cargo:https://github.com/tekumara/typos-lsp" = "latest"
"cargo:lychee" = "latest"
"cargo:typos-cli" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@ls-lint/ls-lint" = "latest"
"npm:autocorrect-node" = "latest"
"pipx:basedpyright" = "latest"
"pipx:ruff" = "latest"
pre-commit = "latest"

# Development Tools
"cargo:https://github.com/bodo-run/yek" = "latest"
"npm:@google/gemini-cli" = "latest"

# Development Tools (Test)
"cargo:genact" = "latest"
"cargo:gfold" = "latest"
"gem:kamal" = "latest"
"gem:rails" = "latest"
"go:code.gitea.io/tea" = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"go:github.com/merschformann/gotz" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@mariozechner/claude-trace" = "latest"
"npm:@openai/codex" = "latest"
"npm:@sourcegraph/amp" = "latest"
"pipx:huggingface_hub" = { version = "latest", cli = "" }
"pipx:llm" = "latest"
"pipx:modal" = "latest"
# "cargo:bartib" = "latest"
# "cargo:bmm" = "latest"
# "cargo:choose" = "latest"
# "cargo:counts" = "latest"
# "cargo:gfold" = "latest"
# "cargo:https://github.com/bodo-run/yek" = "latest"
# "cargo:https://github.com/hanshuaikang/Nping" = "latest"
# "cargo:https://github.com/imsnif/bandwhich.git" = "latest"
# "cargo:https://github.com/KSXGitHub/parallel-disk-usage" = "latest"
# "cargo:https://github.com/lotabout/rargs.git" = "latest"
# "cargo:https://github.com/mfontanini/presenterm" = "latest"
# "cargo:https://github.com/Nukesor/pueue" = "latest"
# "cargo:https://github.com/sirwart/ripsecrets" = "latest"
# "cargo:https://github.com/svenstaro/miniserve" = "latest"
# "cargo:https://github.com/yarrow/zet" = "latest"
# "cargo:https://github.com/yshavit/mdq" = "latest"
# "cargo:just" = "latest"
# "cargo:koji" = "latest"
# "cargo:legdur" = "latest"
# "cargo:lychee" = "latest"
# "cargo:netscanner" = "latest"
# "cargo:pik" = "latest"
# "cargo:rip2" = "latest"
# "cargo:rnr" = "latest"
# "cargo:rust-parallel" = "latest"
# "cargo:sd" = "latest"
# "cargo:sigrs" = "latest"
# "cargo:spacer" = "latest"
# "cargo:tokei" = "latest"
# "cargo:typos-cli" = "latest"
# "cargo:viddy" = "latest"
# "cargo:watchexec-cli" = "latest"
# "cargo:xh" = "latest"
# "gem:kamal" = "latest"
# "go:code.gitea.io/tea" = "latest"
# "go:github.com/bootdotdev/bootdev" = "latest"
# "go:github.com/josephburnett/jd" = "latest"
# "go:github.com/merschformann/gotz" = "latest"
# "go:github.com/muesli/duf" = "latest"
# "go:github.com/wader/fq" = "latest"
# "go:github.com/zyedidia/eget" = "latest"
# "npm:@anthropic-ai/claude-code" = "latest"
# "npm:@biomejs/biome" = "latest"
# "npm:@google/gemini-cli" = "latest"
# "npm:@ls-lint/ls-lint" = "latest"
# "npm:@mariozechner/claude-trace" = "latest"
# "npm:@openai/codex" = "latest"
# "npm:@sourcegraph/amp" = "latest"
# "npm:autocorrect-node" = "latest"
# "pipx:argcomplete" = "latest"
# "pipx:basedpyright" = "latest"
# "pipx:commitizen" = "latest"
# "pipx:llm" = "latest"
# "pipx:mcp-proxy" = "latest"
# "pipx:modal" = "latest"
# "pipx:pre-commit" = "latest"
# "pipx:pyrefly" = "latest"
# "pipx:pyright" = "latest"
# "pipx:ruff" = "latest"
# "pipx:sqlfluff" = "latest"
# "pipx:sqlite-utils" = "latest"
# "pipx:ty" = "latest"
# "pipx:vastai" = "latest"
# cosign = "latest"
# just = "latest"
# shellcheck = "latest"
# slsa-verifier = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

trusted_config_paths = ['~/Developer']

[settings.status]
missing_tools = "never"
show_env = false
show_tools = false

[settings.cargo]
binstall = true

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true
