[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
zig = "latest"

"cargo:https://github.com/sirwart/ripsecrets" = "latest"
"cargo:lychee" = "latest"
"cargo:typos-cli" = "latest"
"npm:@ls-lint/ls-lint" = "latest"
"npm:autocorrect-node" = "latest"
"pipx:basedpyright" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:ty" = "latest"

"cargo:gfold" = "latest"
"cargo:https://github.com/bodo-run/yek" = "latest"
"cargo:koji" = "latest"
"cargo:rust-parallel" = "latest"
"cargo:tokei" = "latest"
"gem:kamal" = "latest"
"go:code.gitea.io/tea" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"pipx:argcomplete" = "latest"
"pipx:commitizen" = "latest"
"pipx:llm" = "latest"
"pipx:mcp-proxy" = "latest"
"pipx:sqlite-utils" = "latest"
"pipx:vastai" = "latest"

# "cargo:https://github.com/hanshuaikang/Nping" = "latest"
# "cargo:https://github.com/imsnif/bandwhich.git" = "latest"
# "cargo:https://github.com/KSXGitHub/parallel-disk-usage" = "latest"
# "cargo:https://github.com/lotabout/rargs.git" = "latest"
# "cargo:https://github.com/mfontanini/presenterm" = "latest"
# "cargo:https://github.com/Nukesor/pueue" = "latest"
# "cargo:https://github.com/sirwart/ripsecrets" = "latest"
# "cargo:https://github.com/svenstaro/miniserve" = "latest"
# "cargo:https://github.com/yarrow/zet" = "latest"
# "cargo:https://github.com/yshavit/mdq" = "latest"

# "cargo:bartib" = "latest"
# "cargo:bmm" = "latest"
# "cargo:choose" = "latest"
# "cargo:counts" = "latest"
# "cargo:just" = "latest"
# "cargo:koji" = "latest"
# "cargo:legdur" = "latest"
# "cargo:lychee" = "latest"
# "cargo:netscanner" = "latest"
# "cargo:pik" = "latest"
# "cargo:rip2" = "latest"
# "cargo:rnr" = "latest"
# "cargo:rust-parallel" = "latest"
# "cargo:sd" = "latest"
# "cargo:sigrs" = "latest"
# "cargo:spacer" = "latest"
# "cargo:viddy" = "latest"
# "cargo:watchexec-cli" = "latest"
# "cargo:xh" = "latest"

# "go:github.com/josephburnett/jd" = "latest"
# "go:github.com/merschformann/gotz" = "latest"
# "go:github.com/muesli/duf" = "latest"
# "go:github.com/wader/fq" = "latest"
# "go:github.com/zyedidia/eget" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
status = { missing_tools = "never", show_env = false, show_tools = false }
trusted_config_paths = ['~/dev', '~/dev-work']

[settings.npm]
bun = true

[settings.pipx]
uvx = true
