[tools]
"cargo:gfold" = "latest"
"cargo:https://github.com/bodo-run/yek" = "latest"
"cargo:https://github.com/hanshuaikang/Nping" = "latest"
"cargo:https://github.com/svenstaro/miniserve" = "latest"
"cargo:https://github.com/yshavit/mdq" = "latest"
"cargo:koji" = "latest"
"cargo:netscanner" = "latest"
"gem:kamal" = "latest"
"go:code.gitea.io/tea" = "latest"
"go:github.com/josephburnett/jd" = "latest"
"go:github.com/merschformann/gotz" = "latest"
"go:github.com/zyedidia/eget" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"
"pipx:vastai" = "latest"
bun = "latest"
go = "latest"
node = "latest"
python = "3.13.2"
ruby = "latest"
rust = "stable"
zig = "latest"

[settings]
trusted_config_paths = ['~/Developer']
experimental = true

[settings.npm]
bun = true

[settings.pipx]
uvx = true
