[tools]
  "cargo:openapi-tui"                          = "latest"
  "cargo:parallel-disk-usage"                  = "latest"
  "cargo:rip2"                                 = "latest"
  "cargo:serie"                                = "latest"
  "cargo:termscp"                              = "latest"
  "cargo:ttyper"                               = "latest"
  "go:github.com/appleboy/CodeGPT/cmd/codegpt" = "latest"
  "npm:bun"                                    = "latest"
  "npm:vercel"                                 = "latest"
  "npm:wrangler"                               = "latest"
  "npm:zeabur"                                 = "latest"
  elixir                                       = "latest"
  go                                           = "latest"
  node                                         = "latest"
  python                                       = "latest"
  zig                                          = "latest"

[settings]
  experimental                          = true
  plugin_autoupdate_last_check_duration = '1 week'
  status                                = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
  trusted_config_paths                  = ['~/Coding']
