[tools]
"cargo:kbt" = "latest"
"cargo:koji" = "latest"
"cargo:openapi-tui" = "latest"
"cargo:parallel-disk-usage" = "latest"
"cargo:rip2" = "latest"
"cargo:serie" = "latest"
"cargo:termscp" = "latest"
"cargo:ttyper" = "latest"
"go:github.com/appleboy/CodeGPT/cmd/codegpt" = "latest"
"go:github.com/melkeydev/go-blueprint" = "latest"
"npm:bun" = "latest"
"npm:promptfoo" = "latest"
go = "latest"
node = "latest"
python = "3.12.7"

[settings]
experimental = true
plugin_autoupdate_last_check_duration = '1 week'
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
trusted_config_paths = ['~/Developer']
