[tools]
"cargo:koji" = "latest"
"cargo:netscanner" = "latest"
"cargo:pik" = "latest"
"cargo:tantivy-cli" = "latest"
"gem:kamal" = "latest"
"go:github.com/josephburnett/jd" = "latest"
"go:github.com/merschformann/gotz" = "latest"
"pipx:ttok" = "latest"
bun = "latest"
go = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
zig = "latest"

[settings]
trusted_config_paths = ['~/Developer']
experimental = true

[settings.pipx]
uvx = true
