[tools]
"cargo:koji" = "latest"
"go:github.com/appleboy/CodeGPT/cmd/codegpt" = "latest"
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
rust = "latest"
zig = "latest"

[settings]
trusted_config_paths = ['~/Developer']
experimental = true

[settings.pipx]
uvx = true
