[tools]
  "cargo:cmd-wrapped"                          = "latest"
  "cargo:csvlens"                              = "latest"
  "cargo:huniq"                                = "latest"
  "cargo:kbt"                                  = "latest"
  "cargo:koji"                                 = "latest"
  "cargo:openapi-tui"                          = "latest"
  "cargo:parallel-disk-usage"                  = "latest"
  "cargo:rip2"                                 = "latest"
  "cargo:serie"                                = "latest"
  "cargo:termscp"                              = "latest"
  "cargo:ttyper"                               = "latest"
  "go:github.com/appleboy/CodeGPT/cmd/codegpt" = "latest"
  "go:github.com/melkeydev/go-blueprint"       = "latest"
  "go:github.com/pouriyajamshidi/tcping/v2"    = "latest"
  "npm:@biomejs/biome"                         = "latest"
  "npm:bun"                                    = "latest"
  "npm:promptfoo"                              = "latest"
  "npm:single-file-cli"                        = "latest"
  "pipx:chainforge"                            = "latest"
  "pipx:datasette"                             = "latest"
  "pipx:deepl-cli"                             = "latest"
  "pipx:detect-secrets"                        = "latest"
  "pipx:fava"                                  = "latest"
  "pipx:huggingface-hub"                       = "latest"
  "pipx:llm"                                   = "latest"
  "pipx:mackup"                                = "latest"
  "pipx:pre-commit"                            = "latest"
  "pipx:ruff"                                  = "latest"
  "pipx:sqlite-utils"                          = "latest"
  "pipx:ttok"                                  = "latest"
  "pipx:vastai"                                = "latest"
  go                                           = "latest"
  node                                         = "latest"
  python                                       = "3.13.1"
  rust                                         = "latest"
  uv                                           = "latest"

[settings]
  experimental                          = true
  plugin_autoupdate_last_check_duration = '1 week'
  status                                = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
  trusted_config_paths                  = ['~/Developer']
