name: build
on: [push, pull_request]
jobs:
  ci:
    name: run
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up macOS
        run: |
          git clone --depth 1 https://github.com/Spehhhhh/dotfiles.git "$HOME"/dotfiles
          cd "$HOME"/dotfiles
          sh ./scripts/bootstrap.sh --force
      - name: Run test
        run: |
          /bin/zsh ./test/test_mac.sh
